post:
  operationId: utilConfigPath
  tags:
    - util
  summary: Get system config
  security:
    - bearerAuth: []
  parameters:
    - $ref: "../../headers/acceptLanguageHeader.yaml"
    - name: configKey
      in: path
      required: true
      schema:
        type: string
  allOf:
    - $ref: "../../response/commonErrorResponses.yaml"
    - responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                type: object
                allOf:
                  - $ref: "../../response/commonResponseProperties.yaml"
                  - properties:
                      data:
                        type: object
                        properties:
                          configValue:
                            type: string
