name: famapp
description: Family App.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.8.21+06081

environment:
  sdk: '>=3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
#  rxdart: 0.22.0
  famapp_api:
    path: ./openapi_gen



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
#  assets_audio_player: ^3.1.1
  background_downloader: ^8.0.5
  badges: ^3.0.2
  cached_network_image: ^3.3.0
  # cached_video_player: ^2.0.4
  video_player: ^2.8.2
  camera: ^0.10.3+2
  carousel_slider: ^4.2.1
  crypto: ^3.0.3
  cupertino_icons: ^1.0.6
  dart_ping: ^9.0.1
  dart_ping_ios: ^4.0.2
  dart_pusher_channels: ^1.2.2
  device_info_plus: ^10.1.0
  dio: ^5.4.0
  extended_image: ^8.2.0
  ffmpeg_kit_flutter: ^6.0.3
  file_picker: ^6.1.1
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
  flutter_cache_manager: ^3.3.1
  flutter_downloader: ^1.10.2
  flutter_html: ^3.0.0-alpha.5
  flutter_image_slideshow: ^0.1.4
  flutter_keyboard_visibility: ^6.0.0
  flutter_launcher_icons: ^0.12.0
  flutter_native_splash: ^2.4.1
  flutter_pickers: ^2.1.9
  flutter_quill: ^9.3.21
  flutter_secure_storage: ^8.0.0
  flutter_slidable: ^2.0.0
  flutter_sms: ^2.3.3
  gcloud: ^0.8.12
  googleapis_auth: ^1.4.1
  google_fonts: ^4.0.4
  google_nav_bar: ^5.0.6
  grouped_list: ^5.1.2
  http: ^1.0.0
  image: ^4.0.17
  image_picker: ^1.1.2
  images_picker: ^1.2.11
  image_gallery_saver: ^2.0.3
  internet_connection_checker_plus: ^2.1.0
  intl: 0.19.0
  just_audio: ^0.9.36
  loading_animation_widget: ^1.2.0+4
  local_auth: ^2.3.0
  openapi_generator_annotations: ^6.1.0
  package_info_plus: ^4.0.2
  path: ^1.8.3
  path_provider: ^2.0.13
  permission_handler: ^10.2.0
  photo_view: ^0.14.0
  provider: ^6.1.1
  pull_to_refresh: ^2.0.0
  record: ^5.0.4
  saver_gallery: ^3.0.1
  share_plus: ^7.2.1
  shimmer: ^3.0.0
  sqflite: ^2.3.0
#  syncfusion_flutter_pdfviewer: ^20.4.52
  url_launcher: ^6.3.1
  vibration: ^1.7.5
  video_thumbnail: ^0.5.3
  webview_flutter: ^4.0.6
#  pusher_client: ^2.0.0
  web_socket_channel: ^2.4.0
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_app_badge_control: ^0.0.2
  grpc: ^4.0.1

#  flutter_quill_extensions: ^0.4.0





dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

  openapi_generator: ^6.1.0
  build_runner: ^2.4.13

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # Needed to be enabled for internalization locales
  # to manually generate localization files, run: flutter gen-l10n
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/aurora/
    - assets/cfg/
    - assets/fonts/
    - assets/icon/
    - assets/innovay/
    - assets/ui/
    - assets/ui/baby/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ZiTiQuanWeiJunHei
      fonts:
        - asset: assets/fonts/ZiTiQuanWeiJunHei.ttf
    - family: PingFangGang
      fonts:
        - asset: assets/fonts/PingFang-Gang_Regular.otf
    - family: SourceHanSansSCNormal
      fonts:
        - asset: assets/fonts/SourceHanSansSC-Normal.otf
    - family: SourceHanSansSCRegular
      fonts:
        - asset: assets/fonts/SourceHanSansSC-Regular.otf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
